# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: onlinestore.catalog::lang.system.labels.category

# Model Form Field configuration
form: $/onlinestore/catalog/models/category/fields.yaml

# Model Class name
modelClass: OnlineStore\Catalog\Models\Category

# Default redirect location
defaultRedirect: onlinestore/catalog/categories

# Create page
create:
    title: onlinestore.catalog::lang.system.labels.create_category
    redirect: onlinestore/catalog/categories/update/:id
    redirectClose: onlinestore/catalog/categories

# Update page
update:
    title: onlinestore.catalog::lang.system.labels.edit_category
    redirect: onlinestore/catalog/categories
    redirectClose: onlinestore/catalog/categories

# Preview page
preview:
    title: onlinestore.catalog::lang.system.labels.preview_category
