# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: onlinestore.catalog::lang.system.labels.product

# Model Form Field configuration
form: $/onlinestore/catalog/models/product/fields.yaml

# Model Class name
modelClass: OnlineStore\Catalog\Models\Product

# Default redirect location
defaultRedirect: onlinestore/catalog/products

# Create page
create:
    title: onlinestore.catalog::lang.system.labels.create_product
    redirect: onlinestore/catalog/products/update/:id
    redirectClose: onlinestore/catalog/products

# Update page
update:
    title: onlinestore.catalog::lang.system.labels.edit_product
    redirect: onlinestore/catalog/products
    redirectClose: onlinestore/catalog/products

# Preview page
preview:
    title: onlinestore.catalog::lang.system.labels.preview_product
