# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Currency

# Model Form Field configuration
form: $/onlinestore/catalog/models/currency/fields.yaml

# Model Class name
modelClass: OnlineStore\Catalog\Models\Currency

# Default redirect location
defaultRedirect: onlinestore/catalog/currencies

# Create page
create:
    title: Create Currency
    redirect: onlinestore/catalog/currencies/update/:id
    redirectClose: onlinestore/catalog/currencies

# Update page
update:
    title: Edit Currency
    redirect: onlinestore/catalog/currencies
    redirectClose: onlinestore/catalog/currencies

# Preview page
preview:
    title: Preview Currency
